name: Build and deploy Node.js app to Azure Web App - anjiapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Install PowerShell 7
        uses: actions/setup-powershell@v2
        with:
          pwsh: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, test
        shell: powershell  # Force Windows PowerShell
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: Webapptesting

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: Webapptesting

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'anjiapp'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
