name: Build and deploy Node.js app to Azure Web App - anjiapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: List root directory contents (debugging)
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          npm test --if-present

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Verify publish profile (debugging)
        run: |
          echo "Publish profile length: ${#PUBLISH_PROFILE}"
          echo "First 50 chars: ${PUBLISH_PROFILE:0:50}"
        env:
          PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'anjiapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: Check deployment status
        if: steps.deploy.outcome != 'success'
        run: |
          echo "Deployment failed!"
          echo "Check if the app-name and slot-name are correct."
          echo "Verify the publish profile is valid and not expired."
        shell: bash
